### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mertthesamael** [HATE-Company/Clone-Dictionary#2]
## ToDoList
- [ ] Antd design menu itemler, içeriğe göre conditional style'a sahip olacak.
- [x] Entryler tüm sayfa ile beraber scroll down olacak, sayfa sonu footer.
- [x] Headline scroll yapılsa bile sayfanın üstünde duracak.
- [x] Left sider overflow olmuyor ( fixed position ) 
- [x] Leaderboard iconu değişecek ( ranking-1 / beyaz )
- [x] Leaderboard'da 'most upvoted entries' içerisinde submenu kalmış, kaldırılacak.
- [x] Best Hot New Bronze iconları küçülecek.
- [x] Headera Hate Company Logosu eklenecek
- [ ] Pagination eklenecek ([antd](https://ant.design/components/pagination/)) 10 entry -> next page.
- [x] Ayrı bir branchte githubtaki gibi bir header denenecek. PP yanına + drop down. Submenuler: create hashtag ve create headline. Buradan devam.
- [x] language ve comment altındaki beyaz alan çok uzuyor daha optimize olabilir yüksekliği
- [x] kutu yüksekliğini biraz kısabiliriz (Reply alanı)
- [x] view all butonu -> view all menu itemıyla uğraşmayalım normal sub menu çalışsın ortada da view all yazsın bg rengi bizim website bg renginde [gri] olsun. thats all. view all sub menunun sınırları -gri renk ayrımıyla- belli olsun kafi. kullanıcıya verilmesi gereken hissi verir yine.
- [x] footer -> contact: https://linktr.ee/hateverse
- [x] footer -> about: https://docsend.com/view/gxfuidxznr5a9q97
- [x] footer -> career: https://docs.google.com/forms/d/e/1FAIpQLSctxk-u45mCn6TFhawGtNVe_0sFgeZPhigddeJWpgMwm0pAYw/viewform
- [x] footer -> faq: https://hatecompany.gitbook.io/wikipage/getting-started/welcome
- [x] footer -> instagram: https://www.instagram.com/hatesocials/
- [x] footer -> twitter: https://twitter.com/Hateverse
- [x] footer -> discord: https://discord.gg/kC5RrSfb
- [x] lang dropdown zIndex ayarı
- [x] headline - entry arası & entry - entry arası mesafeler eşitlenmeli
- [x] best hot new kısmını şu verlith'in siyah boxı ile aynı hizada tutabiliriz
- [ ] searchboxtan da sonuç dönmezse, create headline sayfasına yönlendirilecek
- [ ] entrylere nested comments yapısı entegre edilecek.

**Comment by burcuerdogann** [comment]
Nested Comments with HTML, CSS and JS
Tutorial = https://www.youtube.com/watch?v=2GjQzBWdDAc
Github = https://github.com/BeGeos/nested-comments-yt
---
Layout - HTML Code - CSS Code
https://www.nicesnippets.com/snippet/bootstrap-comment-post-design-demo
---
Nested Comments with React
https://www.youtube.com/watch?v=sjAeLwuezxo

**Comment by burcuerdogann** [comment]
Nested Comments with HTML, CSS and JS
Tutorial = https://www.youtube.com/watch?v=2GjQzBWdDAc
Github = https://github.com/BeGeos/nested-comments-yt

Layout - HTML Code - CSS Code
https://www.nicesnippets.com/snippet/bootstrap-comment-post-design-demo

Nested Comments with React
https://www.youtube.com/watch?v=sjAeLwuezxo
